# Docker image configuration
image:
  repository: virgiebebe/hello-world
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx" # Use "traefik" if you're using Traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Apply if TLS is enabled
  hosts:
    - host: example.com # Replace with your domain or localhost if testing locally
      paths:
        - /
  tls:
    - secretName: hello-world-tls # Secret name for TLS certificates
      hosts:
        - example.com # Replace with your domain or localhost if testing locally

# Replication and autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Affinity and Taints
affinity: {}
tolerations: []

# Health checks
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

# Custom labels
labels:
  app: hello-world
