apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: hello-world
  endpoints:
  - port: http
    path: /metrics
